CREATE TABLE ExemploAula
(
	rgmAluno integer,
	nomeAluno varchar(50),
	enderecoAluno varchar(50),
	celular varchar(11)
);

--ALTERE A TABELA ADICIONANDO UMA NOVA COLUNA CHAMADA "DT_NASCIMENTO"
ALTER TABLE ExemploAula ADD COLUMN dt_nascimento DATE;

--RENOMEIE A COLUNA CELULAR PARA TELEFONE
ALTER TABLE ExemploAula RENAME COLUMN celular TO telefone;

-- DELETE A COLUNA DT_NASCIMENTO
ALTER TABLE ExemploAula DROP COLUMN dt_nascimento RESTRICT;

--ALTERE A RESTRIÇÃO DA COLUNA CELULAR PARA QUE NAO POSSA TER VALORES NULOS
ALTER TABLE ExemploAula ALTER COLUMN telefone SET NOT NULL;

-- ALTERE O NOME DA TABELA PARA "CAD_ALUNOS"
ALTER TABLE ExemploAula RENAME TO cad_alunos;